### ISSUE TITLE
Doesn't work in Safari 9.1.1

### ISSUE THREAD

**Issue by freen** [chpio/babel-plugin-transform-promise-to-bluebird#2]
Safari version 9.1.1 (11601.6.17)

I've implemented this plugin exactly as documented, and it works as expected in Firefox 51.0.1 and Chrome 56.0.2924.87.

My smoke test is whether or not the `unhandledrejection` event is being fired / capturable: 

```javascript
if (typeof window !== 'undefined') {
  // See http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events
  window.addEventListener('unhandledrejection', function(e) {
    console.log('Confirmed unhandledrejection listener for this browser.');
    if (typeof e.detail !== 'undefined' && typeof newrelic !== 'undefined') {
      e.preventDefault();
      const exception = e.detail.reason;
      newrelic.noticeError(exception)
    }
  });
}
```

My application has a route which directly fires a Promise rejection. The above console message is logged on the above Chrome and Firefox versions, but not the above Safari version.

Significantly, the stacktrace for the unhandled promise rejection in Safari points to the vanilla es6.promise polyfill file. (`~/core-js/modules/es6.promise.js:117`)

It looks like the override logic isn't behaving as expected for Safari, and the vanilla es6 promise is being used instead. 

![screen shot 2017-03-13 at 1 10 43 pm](https://cloud.githubusercontent.com/assets/1816457/23854008/a855fe8c-07ef-11e7-9ac4-8b07a1eedb8e.png)

**Comment by chpio** [comment]
> Significantly, the stacktrace for the unhandled promise rejection in Safari points to the vanilla es6.promise polyfill file. (~/core-js/modules/es6.promise.js:117)

hmm, the code that generates the promise, is it part of your code (code handled by babel, therefore by promise-to-bluebird) or a dependency (not handled by your babel setup)?

> It looks like the override logic isn't behaving as expected for Safari, and the vanilla es6 promise is being used instead.

there is no "override logic". the transformations are done at "compile time".

**Comment by freen** [comment]
Aha! That seems to make a difference.

A rejected promise created by my application code (not by a vendor) _does_ trigger `'unhandledrejection'` in Safari as well as Chrome / Firefox.

But (as in the example cited in this issue) a rejected promise created outside my application code / by a vendor _doesn't_ trigger `'unhandledrejection'` in Safari, whereas it does trigger this event in Chrome and Firefox.

Case in point, when an exception is raised in a React Component lifecycle function, e.g. `componentDidMount`, it gets wrapped in a promise transparently / by the vendor. That seems to suggest that the use case is pretty significant.

This is the code which triggers the rejected promise, which caused me to create the issue / doesn't trigger `'unhandledrejection'` in Safari:

```javascript
import React, { Component } from 'react';
import { connect } from 'react-redux';

class ThrowUncaughtExceptionInReactComponentLifecycleContainer extends Component {
  componentDidMount() {
    // This ultimately is fired from within a promise, transparently, which is created by React under the hood
    throw new Error("Don't catch this ordinary exception");
  }

  render() {
    return (
      <div>See console. This container should have thrown a simple exception after mount. This is useful for testing which kinds of JavaScript errors are being reported to NewRelic.</div>
    );
  }
}
const mapStateToProps = (state) => {
  return { };
};

const mapDispatchToProps = (dispatch) => {
  return {  };
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ThrowUncaughtExceptionInReactComponentLifecycleContainer);
```

**Comment by freen** [comment]
Is this expected behavior? I'm a bit surprised this works in Chrome / Firefox but not Safari.

**Comment by chpio** [comment]
> Case in point, when an exception is raised in a React Component lifecycle function, e.g. componentDidMount, it gets wrapped in a promise. That seems to suggest that the use case is pretty significant.

In other words: the promise is generated by the "react" package, not your code.

> I'm a bit surprised this works in Chrome / Firefox but not Safari.

i guess that's due to the different implementations of *Promise* in FF/C vs. S

You could try to wrap the Exception into a bluebird promise:
```js
  componentDidMount() {
    return Promise.reject(new Error("Don't catch this ordinary exception"));
  }
```
(im not very familiar with the react api, but maybe it's accepting promises as the return type....)

edit: there has to be a way to get the promise from react and hook it into the promise-chain.

**Comment by freen** [comment]
That's correct, the promise is generated by React.

Sorry, I could have been clearer, in explaining our use case.

We are attempting to report all uncaught Promise rejections to the NewRelic Browser service. To do this, we want to replace the default Promise object with the Bluebird promise object, so that uncaught promise rejections will produce the `'unhandledrejection'` event, and we can do our special handling logic.

React executes its component lifecycle functions within promises, thus, all exceptions which occur inside React component lifecycle functions, become uncaught Promise rejections.

Therefore, in the above example use case, we are explicitly `throw`'ing an exception, to test the behavior of _what would otherwise be an unexpected exception_.

So returning a rejected promise here doesn't help, actually.

I want to be able to handle _unexpected_, uncaught Promise rejections, no matter where those Promises are created --- inside or outside of custom application code, inside or outside of vendor code. I want unexpected exceptions (thus, unexpected / uncaught Promise rejections) to be detected by this handler.

It seems like this is supported functionality in Chrome / Firefox, so now I guess the question is, does the issue in Safari have to do with the way this babel plugin is created? Is there maybe a tweak which is possible, to fix the Safari-promise-rejection-behavior-in-vendor-code use case? Or does Safari fully not support this behavior?

If the behavior works as I described for Chrome / Firefox (detects unhandled rejections for vendor-created Promises,) it seems like the issue could be with the plugin at compile time.

**Comment by freen** [comment]
I think I understand your point better. Babel should have nothing to do with rewriting vendor JavaScript code, thus this plugin shouldn't have an effect on vendor promises.

I'm also noticing in the Chrome console that the same exception is showing up as a vanilla exception _as well as_ a promise. Still, a vanilla uncaught exception would not have triggered `'unhandledrejection'` event, so maybe that doesn't change the conversation?

![screen shot 2017-03-13 at 4 25 44 pm](https://cloud.githubusercontent.com/assets/1816457/23861407/3b674bbc-080a-11e7-8af8-1e12bcfc6289.png)




With that said, our webpack configuration also handles bundling of our vendor files, and I've added `babel-plugin-transform-promise-to-bluebird` to our webpack configuration right along side all of our bundling tasks -- so that may explain why it is (mostly) working, even for vendor promises, which is just what we want.

Still! Safari is unaffected. This is the strangest part :)

**Comment by freen** [comment]
Ah, I was mistaken, only Chrome has this behavior. Firefox and Safari both lack the `unhandledrejection` event for vendor promises. Hmmm

**Comment by freen** [comment]
Aha! It all makes sense now. Only Chrome has this behavior because chrome natively produces this error: http://stackoverflow.com/a/32940253/739373

Nothing to do with your babel plugin :~) Thanks for the help!
